### ISSUE TITLE
Raspberry Pi zero 

### ISSUE THREAD

**Issue by ccfannin69** [aCallum/SafePi#8]
I have it install on a Raspberry Pi 3 and works great.  I tried to install it on a zero and i get this error message.
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    update_data()
  File "main.py", line 105, in update_data
    currentRate = (float)(ticker['info']['last'])
UnboundLocalError: local variable 'ticker' referenced before assignment

**Comment by ccfannin69** [comment]
I have it up and running....
